(SELECT  'uxxOLDAXiGu' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'QjjvoGauFeg' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_01_06_M	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'uxxOLDAXiGu' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'FEiFPNM8R1d' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_01_06_F	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'iokiEFhlfGH' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'MopUpXiLXlM' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_01_06_0_14	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'iokiEFhlfGH' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'oTUqr9J56DK' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_01_06_15	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'KGhcTgNKGbo' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'TEDC8NdJPry' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_01_06_pre	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'KGhcTgNKGbo' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'wTz6csmCAiz' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_01_06_ART	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'dcz25pp8iO4' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'QjjvoGauFeg' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_02_05_M	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'dcz25pp8iO4' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'FEiFPNM8R1d' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_02_05_F	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'eyrhXw0TgaH' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'MopUpXiLXlM' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_02_05_0_14	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'eyrhXw0TgaH' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'oTUqr9J56DK' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_02_05_15	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'kEP1XXGq3Dv' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'TEDC8NdJPry' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_02_05_pre	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'kEP1XXGq3Dv' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'wTz6csmCAiz' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_02_05_ART	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'ExonxwofHup' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'QjjvoGauFeg' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_M	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'ExonxwofHup' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'FEiFPNM8R1d' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_F	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'UreEMyTGSXL' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'Y9e8HJVeLOH' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_0_4	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'UreEMyTGSXL' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'H00exThzgWA' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_5_14	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'UreEMyTGSXL' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'oTUqr9J56DK' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_15	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'EOFO1XAQmgs' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'TEDC8NdJPry' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_pre	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'EOFO1XAQmgs' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'wTz6csmCAiz' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_ART	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'MpRf5S2KxhQ' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_04_01_enrolled	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'uGr2ZLU6FWq' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'QjjvoGauFeg' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_05_06_M	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'uGr2ZLU6FWq' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'FEiFPNM8R1d' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_05_06_F	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'sNLUnwXT0vI' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'TEDC8NdJPry' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_05_06_pre	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'sNLUnwXT0vI' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'wTz6csmCAiz' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_05_06_ART	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'bCcXal9Ijwg' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'QjjvoGauFeg' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_M	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'bCcXal9Ijwg' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'FEiFPNM8R1d' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_F	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'fNK5vrvm6cM' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'Y9e8HJVeLOH' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_0_4	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'fNK5vrvm6cM' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'H00exThzgWA' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_5_14	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'fNK5vrvm6cM' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'oTUqr9J56DK' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_15	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'MFaBv34Zjej' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'TEDC8NdJPry' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_pre	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'MFaBv34Zjej' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'wTz6csmCAiz' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_ART	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'EtqkzcUecPE' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_preg	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'bgp9pkXkQzf' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_09_04_TB	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'cPM6nAf3fQc' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'Y9e8HJVeLOH' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_0_4	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'cPM6nAf3fQc' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'MopUpXiLXlM' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_0_14	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'cPM6nAf3fQc' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'oTUqr9J56DK' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_15	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'jeSKaCwwQM9' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'P2dEM4wZGn4' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_men350	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'jeSKaCwwQM9' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'q7k7VZrK7Ve' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_mai350	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'mdMCW3A4nZJ' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_preg	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'E9QCyrRKBBx' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_12_04_TB	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'FAK1QJWYFYH' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'QjjvoGauFeg' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_M	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'FAK1QJWYFYH' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'FEiFPNM8R1d' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_F	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'kv3FDDJt0g1' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'Y9e8HJVeLOH' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_0_4	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'kv3FDDJt0g1' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'H00exThzgWA' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_5_14	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'kv3FDDJt0g1' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'oTUqr9J56DK' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_15	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'IwJCrDLNQY5' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'TEDC8NdJPry' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_pre	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'IwJCrDLNQY5' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'wTz6csmCAiz' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.CLC_18_07_ART	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) 