(SELECT  'GTKoHfJWJh3' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.A1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'aNEf1lz9CPQ' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.A2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'ABgYSUDHarm' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.A3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'GYq8LZ1A2Wb' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.B1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'JAlGj2Mf8di' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.B2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'BCYjEpldSxo' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.B3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'T046iJRZfrf' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.C1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'Pnt8JrB9Ynn' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.C2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'o2RSHkZj28Z' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.C3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'S39E7qbzXGJ' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.D1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'Tixbe7lozVt' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.D2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'bH8SKaOTywE' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.D3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'egjEHbsd0O5' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.E1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'KuAczvbEfwo' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.E2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'clOSJGv5mo8' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.E3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'FyehWXnqEQJ' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.F1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'l6i9pVK2ky2' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.F2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'XAqrE2VAhwg' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.F3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'snbA7M2L0lW' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.G1	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'eb9SyqemIoh' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.G2	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'Tf3OBR0rmCY' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.G3	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION

(SELECT  'UWrg94ClYmm' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.H	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'WakKUuhaikn' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.I	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'p7oikGEgExV' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.J	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) UNION
(SELECT  'KcjFwoYYNr5' AS dataelement,`'DATA SOURCE$'`.Period_uid AS period,`'DATA SOURCE$'`.DHIS_US_uid AS orgunit,'jF6cd1dU990' AS categoryoptioncombo,'' AS attroptioncombo,`'DATA SOURCE$'`.K	AS value,'openmrs.reporting' AS storedby,timestamp AS timestamp FROM `'DATA SOURCE$'` `'DATA SOURCE$'`) 